import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/assets/styles/globals.css';
import { getNavigationData } from '@/data/loaders';
import Header from '@/components/layout/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  subsets: ['latin', 'cyrillic-ext', 'greek'],
  display: 'swap',
  weight: ['100', '300', '400', '500', '700', '900'],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigationData = await getNavigationData();

  return (
    <html lang="ru" className={`${roboto.className}  antialiased`}>
      <body>
        <Header navigationData={navigationData.data} />
        {children}
      </body>
    </html>
  );
}
